### ISSUE TITLE
missing dependency json8-pointer from merge-patch

### ISSUE THREAD

**Issue by ashnur** [sonnyp/JSON8#55]
Installing just json8-merge-patch fails with error at this line:
https://github.com/sonnyp/JSON8/blob/master/packages/merge-patch/lib/toJSONPatch.js#L4

**Comment by ashnur** [comment]
What are your thoughts about https://docs.npmjs.com/files/package.json#peerdependencies?

**Comment by ashnur** [comment]
I use browserify, babel so the code is first run in node, then in the browser :)

**Comment by sonnyp** [comment]
https://github.com/sonnyp/JSON8/pull/59
