### ISSUE TITLE
Any particular reason for using null as a prototype?

### ISSUE THREAD

**Issue by ashnur** [sonnyp/JSON8#56]
https://github.com/sonnyp/JSON8/blob/master/packages/merge-patch/lib/apply.js#L18
because of this line, nested objects will not have usual Object.prototype.methods in the prototype chain and fails at this line https://github.com/sonnyp/JSON8/blob/monorepo/packages/merge-patch/lib/diff.js#L20

May I ask how I can use these modules installed from npm such that they are not failing at hidden tight couplings of datatypes? :)

**Comment by sonnyp** [comment]
Nit picking but null is not used as the prototype, `Object.create(null)` just created an object without any prototype.

Anyway, good catch, will fix

**Comment by ashnur** [comment]
http://www.ecma-international.org/ecma-262/8.0/index.html#sec-object.create

> Let obj be ObjectCreate(O).

http://www.ecma-international.org/ecma-262/8.0/index.html#sec-objectcreate

> Set obj.[[Prototype]] to proto.

I interpret this as: If proto was `null`, you set the prototype to `null`. But we can get philosophical about it too, delve into the depths of meaning and existence, and the meaning of existence...

**Comment by sonnyp** [comment]
https://github.com/sonnyp/JSON8/pull/59

**Comment by ashnur** [comment]
I switched to another library, but will try json8 again after this change. Thank you.
